### ISSUE TITLE
Add in Demo/Guide in main README showcasing how to dynamically add in new CellProvider

### ISSUE THREAD

**Issue by 10000TB** [DianQK/Flix#20]
Often times in real app, there are async requests return after viewDidLoad, and we want to update UI upon that return. In this particular context of Flix, main README does not document how to dynamically add in new cellProvider, but it seems there are ways to achieve that with Flix. So it would be nice to add a new section for that.

@DianQK  Wdyt ?

**Comment by DianQK** [comment]
Just call `build`, but you can hide this provider's values.

**Comment by 10000TB** [comment]
`build` works. 

But I notice that when I am call `build` second time, there is a short period of view freezing (in a sense where you cannot scroll, and re-`build` process also brings in some unwanted animation

**Comment by DianQK** [comment]
try this code:
```swift
tableView.flix.animatable.build(providers).decideViewTransition = { changesetInfos in
    // ...
    return ViewTransition.reload
}
```

**Comment by 10000TB** [comment]
Huge thanks @DianQK !
