### ISSUE TITLE
Xcode 10 Swift 4.2 build failed

### ISSUE THREAD

**Issue by arexdra** [DianQK/Flix#22]
This is my Podfile:
<img width="314" alt="image" src="https://user-images.githubusercontent.com/42928095/46509195-dda25e00-c873-11e8-8755-0b65fb839202.png">

But when I build the project, error happens:
<img width="458" alt="image" src="https://user-images.githubusercontent.com/42928095/46509234-15a9a100-c874-11e8-949c-85d26685254a.png">

**Comment by DianQK** [comment]
try `pod 'Flix', '~> 2.0'`
