### ISSUE TITLE
pod search flix  

### ISSUE THREAD

**Issue by LGLee** [DianQK/Flix#7]
not support cocoapods?

**Comment by DianQK** [comment]
Please run `pod repo update` before search Flix.

https://cocoapods.org/?q=flix

**Comment by LGLee** [comment]
yes , I did, But still can't find it...  pod version is 1.2.1 , gem source is https://ruby.taobao.org/

**Comment by DianQK** [comment]
Please check you have add https://github.com/CocoaPods/Specs.git.

https://github.com/CocoaPods/Specs/commit/d50f88652f88044703b28c3e145133f84c6ab888
