### ISSUE TITLE
Build Failed Task failed with exit code 65:

### ISSUE THREAD

**Issue by sixty8** [DianQK/Flix#8]
*** Building scheme "Flix" in Flix.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace ... -scheme Flix -configuration Release -derivedDataPath ../org.carthage.CarthageKit/DerivedData/9.1_9B55/Flix/1.0.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath ./ SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO (launched in /Users/..)

i use xcode 9.1 with carthage update --platform iOS --no-use-binaries
what i'm missing?

**Comment by DianQK** [comment]
ooo..

This is my mistake, I will release new version after #9 passed.

Now you can try `github "DianQK/Flix" "fix-carthage"`
